---
title: "Google Trends - Termo Dengue de 2004 à 2018"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)

library(flexdashboard)
library(gtrendsR)
library(dygraphs)
library(xts)
library(dplyr)
library(magrittr)
library(lubridate)

# dados google trend

dengue <- gtrends(c("Dengue"), geo = "BR", time = "all")  

# dados dengue datasus

datasus <- read.csv2("dengue_datasus.csv", skip = 3) %>% as_tibble()

```

Column {data-width=550}
-----------------------------------------------------------------------

### Interesse por região

```{r}
library(rgdal)
library(RColorBrewer)
S1 <- readOGR("./BRUFE250GC_SIR", "BRUFE250GC_SIR",
              verbose = FALSE,
              stringsAsFactors = FALSE,
              encoding = "utf-8",
              use_iconv = TRUE)

dados2 <- dengue$interest_by_region
dados2[, 'location'] <- iconv(dados2[, 'location'], from = "utf-8", to = "iso8859-1")
dados2[, 'location'] <- toupper(ifelse(dados2[, 'location'] == "Federal District",
                                       "Distrito Federal",
                                       substr(dados2[, 'location'], 10,
                                              nchar(dados2[, 'location']))))

dados2 <- subset(dados2, select = c(location,hits))
rownames(dados2) <- dados2$location
S1$z <- dados2[S1$NM_ESTADO, 'hits']
S1$qz <- cut(S1$z, quantile(S1$z), include.lowest = TRUE)

require(leaflet)

qpal <- colorQuantile(
  "RdYlBu",
  S1$z,
  n = 4, reverse = TRUE)

map <- leaflet(data = S1)
map %>% setView(-51.33, -15.22 , zoom = 4) %>% 
  addTiles('http://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png', attribution = 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>') %>% 
  addPolygons(fill = TRUE, 
              stroke = TRUE, 
              color = ~qpal(z),
              smoothFactor = 0.2, 
              fillOpacity = .5) %>% 
  addLegend(pal = qpal,
            values = ~z,
            opacity = 1,
            title="Hits Dengue")
```

Column {data-width=450}
-----------------------------------------------------------------------

### Hits de 2004 - 2018 e Taxa de incidência de 2004 - 2012

```{r}

dados <- subset(dengue$interest_over_time, select = c(date, hits))

dados %<>% as_tibble() %>% 
  left_join(x = ., 
            y = datasus %>% 
              mutate(date = Ano %>% ymd(truncated = 2)), 
            by = "date")

colnames(dados) <- c("date", "hits", "ano", "txi")

dados %<>% select(-ano) 

dados %<>% xts(dados[, -1], order.by = dados[, 1] %>% pull)

dygraph(dados[, -1]) %>%
  dyAxis("y", label = "Hits", valueRange = c(0, 100), 
         independentTicks = TRUE) %>% 
  dyAxis("y2", label = "Taxa de incidência", valueRange = c(0, 600), 
         independentTicks = TRUE) %>% 
  dySeries("hits",  axis = ("y"), fillGraph = TRUE) %>%
  dySeries("txi",  axis = ("y2"), pointSize = 3) %>% 
  dyRangeSelector(height = 15) %>% 
  dyOptions(connectSeparatedPoints = TRUE)
```

### Termos associados

```{r}
require(d3wordcloud)

dados3 <- subset(dengue$related_queries, related_queries == "top",
                 select = c(subject, value))
dados3$value <- iconv(dados3$value, from = "utf-8", to = "iso8859-1")

set.seed(1235)
d3wordcloud(words = dados3$value, freq = dados3$subject,
            colors = brewer.pal(6, "Dark2"),
            spiral = "archimedean")
```

